### ISSUE TITLE
OpenTK 4 support?

### ISSUE THREAD

**Issue by pigLoveRabbit520** [hjoykim/THREE#22]
Can this repo be compiled on Linux?

**Comment by hjoykim** [comment]
Hello,
this code are using OpenTK 4 .Net Framework
so it's support to window platform only.
I tried several ways to get it to compile on Linux, but I got some errors. One of them was using the [OpenTK.GLControl Winforms Control .Net core version 3.1](https://github.com/opentk/GLControl)
but this version of GLControl didn't seem to run three.js' glsl properly.
I haven't been able to fix it yet.

**Comment by pigLoveRabbit520** [comment]
**https://github.com/hjoykim/THREE/tree/master/THREE** this repo should be compiled on Linux, it should be a underlying library, nothing with GUI.

**Comment by hjoykim** [comment]
Let's examine how it can be split into two parts: THREE and THREE.controls. However, since I am currently working hard for a living, it may take a long time.
If you have any good ideas please tell me

**Comment by xtuzy** [comment]
I use [threejs4net](https://github.com/xtuzy/threejs4net/tree/veldridrender) and split core library to netstandard2.0, not reference opentk, use a single project to use opentk render, because i see current threejs will support webgpu.

I see demo of THREE work well than threejs4net, so try do it in THREE, but many code use api of opengl.

**Comment by hjoykim** [comment]
OK, I'll check it
Thanks you
