### ISSUE TITLE
Light hint

### ISSUE THREAD

**Issue by merco** [hjoykim/THREE#36]
How can I get a visualisation like the right one?

![immagine](https://github.com/user-attachments/assets/aa4a5e1e-1837-496c-a5d7-4ca5f2373161)

What kind of light should I use?

![immagine](https://github.com/user-attachments/assets/65ae146f-c8e4-4e4f-bd7d-94d2bb9427f4)

[80038032{18}.zip](https://github.com/user-attachments/files/17071012/80038032.18.zip)

**Comment by hjoykim** [comment]
Hello,
The reason the right and left sides look different is because the positions of the lights are different.
On the right side, the light's position appears to be set according to the camera's position.

Please refer to the attached example of setting the light position according to the camera position.

![image](https://github.com/user-attachments/assets/20485c7f-01a4-45e3-973e-357099c99c5e)
[LightHintExample.zip](https://github.com/user-attachments/files/17083314/LightHintExample.zip)

**Comment by merco** [comment]
@hjoykim 

I'm having some difficulty with PointLight.

The image rendering is much better with PointLight but compared to the view on the left it remains darker for me: perhaps a positioning problem.


I saved camera position and light info from a threejs model in the "modeldata.dat" file. 

![immagine](https://github.com/user-attachments/assets/2325d717-0df3-472c-a0c7-2b0e33e2c2d6)


[Lights.zip](https://github.com/user-attachments/files/17265491/Lights.zip)

[sample_1m_lights.zip](https://github.com/user-attachments/files/17265490/sample_1m_lights.zip)
